### ISSUE TITLE
Building container fails

### ISSUE THREAD

**Issue by keenlooks** [NVlabs/DiffPure#1]
The first installation command fails for me when building the Docker container. Error can be recreated by cloning the repo, cd into it, and run the installation command:

`docker build -f diffpure.Dockerfile --tag=diffpure:0.0.1 .`

I've attached a txt with the build output: [build_output.txt](https://github.com/NVlabs/DiffPure/files/8922442/build_output.txt)

I've tried troubleshooting these errors by removing the version numbers from the pip install command in the Dockerfile like this:

`RUN pip install numpy \
                pyyaml \
                wheel \
                scipy \
                torch \
                torchvision \
                pillow \
                matplotlib \
                tqdm \
                tensorboardX \
                seaborn \
                pandas \
                requests \
                xvfbwrapper \
                torchdiffeq \
                timm \
                foolbox \
                torchsde \
                git+https://github.com/RobustBench/robustbench.git \`

but then get different errors, which is here: [build_output_versions_removed.txt](https://github.com/NVlabs/DiffPure/files/8922443/build_output_versions_removed.txt)

Do any of these errors seem familiar? Do you know how to fix them? Any help would be appreciated.

I did notice that robustbench recently updated. Is there a specific version of robustbench I should be using?

**Comment by weilinie** [comment]
Hi @keenlooks, thanks for poining out this issue. I've updated the dockerfile to solve it. Let me know if you have further issues. To answer your question, the incompatibility issue happens after I switched from `robustbench v0.1` to the latest version  of `robustbench` by using `pip install git+https://github.com/RobustBench/robustbench.git`, and you can see a similar issue [here](https://github.com/RobustBench/robustbench/issues/83). I suggest using the latest version  of `robustbench` because otherwise automatic downloading of the models may not work.

**Comment by keenlooks** [comment]
Thanks! This fixed the build issue for me.
