### ISSUE TITLE
Questions about the fixed subset.

### ISSUE THREAD

**Issue by zzzhangboya** [NVlabs/DiffPure#10]
Hi, I have some questions about the fixed subset size used in cifar10 and imagenet.
The paper says it used a fixed subset of **512** images that is randomly sampled from the test set for cifar10 and imagenet. 
And in the readme.md, for the autoattack in cifar10, you suggests **8** different data seeds, for bpda in cifar10, **5** seeds, and for autoattack in imagenet, **16** seeds.
However in the run_script folder, the num_sub variables are set **64, 200, 16,** respectively.
Only **64x8=512** matches paper, **200x5, 16x16** don't match.

**Comment by weilinie** [comment]
Hi @zzzhangboya, thanks for pointing out this issue. For ImageNet, there should be 32 seeds, which I have updated in the readme. For BPDA on CIFAR-10, we used 200x5 samples (rather than 512) to evaluate our method and all the baselines. Sorry this difference has not been reflected in the paper, but we note that the results on 1000 and 512 samples should be very close.
