### ISSUE TITLE
Backprop through SDE

### ISSUE THREAD

**Issue by KMnP** [NVlabs/DiffPure#4]
Hi, thank you for sharing the code! I wonder if it's possible for you to point to the code which computes the gradient of SDE by solving the augmented SDE (Sec 3.2, Proposition 3.3.). 

I could see that in https://github.com/NVlabs/DiffPure/blob/master/bpda_eot/bpda_eot_attack.py#L98 returns the grads w.r.t. the purified image, and the output `attack_grad` is directly used in https://github.com/NVlabs/DiffPure/blob/master/bpda_eot/bpda_eot_attack.py#L86 to update the adv images. Maybe I missed something, I did not see the function to solve the augmented SDE (Eq.6)

Thank you for your help!

**Comment by weilinie** [comment]
Thanks for your interest in our work. For your questions: (1) The BPDA attack does not need to backprop through SDE. Instead, it uses the identity approximation (or straight-through) to bypass the SDE part during the gradient computation. (2) We didn't explicitly write the implementation of solving the augmented SDE on our own. Rather, we used the adjoint method in the [`torchsde`](https://github.com/google-research/torchsde) package (e.g., [this line](https://github.com/NVlabs/DiffPure/blob/master/runners/diffpure_sde.py#L236)) to compute the gradient of SDE. 

Hope we answered your questions.

**Comment by thuwzy** [comment]
> Thanks for your interest in our work. For your questions: (1) The BPDA attack does not need to backprop through SDE. Instead, it uses the identity approximation (or straight-through) to bypass the SDE part during the gradient computation. (2) We didn't explicitly write the implementation of solving the augmented SDE on our own. Rather, we used the adjoint method in the [`torchsde`](https://github.com/google-research/torchsde) package (e.g., [this line](https://github.com/NVlabs/DiffPure/blob/master/runners/diffpure_sde.py#L236)) to compute the gradient of SDE.
> 
> Hope we answered your questions.

How about the gradient of `ddpm` and `guided_diffusion`? I didn't find any use of `torchsde` in these files. 

Thank you for your help!

**Comment by weilinie** [comment]
Do you mean the files `diffpure_ddpm.py` and `diffpure_guided.py`? They still use the discrete formulation of the diffusion process, so we didn’t apply `torchsde` there. We kept them in the repo because 1) we wanted to verify if continuous and discrete formulations are equivalent given the same pertained models, and 2) some attacks don’t need to backprop through the diffusion process so we can still use them for evaluation. 

That said, when you plan to backprop through the diffusion process, I recommend you always choose either `sde` or `ode` as the `diffusion_type`.

**Comment by thuwzy** [comment]
I see. Thank you for your reply.
