### ISSUE TITLE
Question about AutoAttack settings

### ISSUE THREAD

**Issue by YihanWu95** [NVlabs/DiffPure#9]
Hi, thank you for sharing the code and models! I find in the code https://github.com/NVlabs/DiffPure/blob/8cbd649736b36314fa0bce035e797b09d787c87d/eval_sde_adv.py#L101 
https://github.com/NVlabs/DiffPure/blob/8cbd649736b36314fa0bce035e797b09d787c87d/eval_sde_adv.py#L114
the parameters 'version' and 'attacks_to_run' in AutoAttack class are assigned value together. However, in the AutoAttack package it's not allowed to do so. 
https://github.com/fra31/auto-attack/blob/b7f560b229145e6e90613cd3ce98cad6a94bd623/autoattack/autoattack.py#L27
I wonder if you use a different version of AutoAttack.

**Comment by weilinie** [comment]
Hi @YihanWu95, thanks for your interest in our work. We didn't use a different version of AutoAttack, for both `rand` and `standard` attack versions, their attack list and the corresponding parameters are kept exactly the same with the default Attack settings. We provided an option to modify the attack version because, in experiments, we wanted to test some customized attacks (e.g., Square attack only).

**Comment by YihanWu95** [comment]
Thanks for your reply, this is indeed a great work!
